FROM debian:stable-slim

RUN apt-get update -y && apt-get -y install sudo git make gcc autoconf pkg-config xorg-dev x11-apps exuberant-ctags imagemagick python3 python3-matplotlib python3-pandas r-base gnuplot tzdata python-is-python3 zsh texlive-latex-base

CMD ["bash"]
